run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - node_modules

linters:
  enable:
    - gofmt
    - govet
    - staticcheck
    - errcheck
    - gosimple
    - ineffassign
    - unused
    - typecheck
    - bodyclose
    - noctx
    - gocyclo
    - gosec
    - misspell
    - unconvert

linters-settings:
  gocyclo:
    min-complexity: 15
  gosec:
    excludes:
      - G404 # Use of weak random number generator

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
