// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

type EntityState struct {
	ID        string `json:"id"`
	EntityID  string `json:"entity_id"`
	ScopeID   string `json:"scope_id"`
	Timestamp string `json:"timestamp"`
	Features  string `json:"features"`
	Labels    string `json:"labels"`
	Meta      string `json:"meta"`
	Adapter   string `json:"adapter"`
	CreatedAt string `json:"created_at"`
}

type Signal struct {
	ID              string  `json:"id"`
	ScopeID         string  `json:"scope_id"`
	SeriesID        string  `json:"series_id"`
	Pattern         string  `json:"pattern"`
	DetectedAt      string  `json:"detected_at"`
	WindowStart     string  `json:"window_start"`
	WindowEnd       string  `json:"window_end"`
	Strength        float64 `json:"strength"`
	Confidence      float64 `json:"confidence"`
	Metrics         string  `json:"metrics"`
	Explanation     string  `json:"explanation"`
	ConfidenceClass string  `json:"confidence_class"`
}

type SignalEvidence struct {
	SignalID string  `json:"signal_id"`
	SeriesID string  `json:"series_id"`
	Time     string  `json:"time"`
	Kind     string  `json:"kind"`
	Score    float64 `json:"score"`
	Metrics  string  `json:"metrics"`
}
