// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlcgen

import "context"

const countEntityStates = `-- name: CountEntityStates :one
SELECT COUNT(*) FROM entity_states WHERE adapter = ?
`

func (q *Queries) CountEntityStates(ctx context.Context, adapter string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEntityStates, adapter)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteOldEntityStates = `-- name: DeleteOldEntityStates :exec
DELETE FROM entity_states
WHERE timestamp < ? AND adapter = ?
`

type DeleteOldEntityStatesParams struct {
	Timestamp string `json:"timestamp"`
	Adapter   string `json:"adapter"`
}

func (q *Queries) DeleteOldEntityStates(ctx context.Context, arg DeleteOldEntityStatesParams) error {
	_, err := q.db.ExecContext(ctx, deleteOldEntityStates, arg.Timestamp, arg.Adapter)
	return err
}

const getEntityStatesByEntity = `-- name: GetEntityStatesByEntity :many
SELECT id, entity_id, scope_id, timestamp, features, labels, meta, adapter, created_at FROM entity_states
WHERE entity_id = ?
ORDER BY timestamp DESC
`

func (q *Queries) GetEntityStatesByEntity(ctx context.Context, entityID string) ([]EntityState, error) {
	rows, err := q.db.QueryContext(ctx, getEntityStatesByEntity, entityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EntityState{}
	for rows.Next() {
		var i EntityState
		if err := rows.Scan(
			&i.ID, &i.EntityID, &i.ScopeID, &i.Timestamp,
			&i.Features, &i.Labels, &i.Meta, &i.Adapter, &i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntityStatesByScope = `-- name: GetEntityStatesByScope :many
SELECT id, entity_id, scope_id, timestamp, features, labels, meta, adapter, created_at FROM entity_states
WHERE scope_id = ?
ORDER BY timestamp DESC
`

func (q *Queries) GetEntityStatesByScope(ctx context.Context, scopeID string) ([]EntityState, error) {
	rows, err := q.db.QueryContext(ctx, getEntityStatesByScope, scopeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EntityState{}
	for rows.Next() {
		var i EntityState
		if err := rows.Scan(
			&i.ID, &i.EntityID, &i.ScopeID, &i.Timestamp,
			&i.Features, &i.Labels, &i.Meta, &i.Adapter, &i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertEntityState = `-- name: InsertEntityState :exec
INSERT INTO entity_states (id, entity_id, scope_id, timestamp, features, labels, meta, adapter, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    features = excluded.features,
    labels = excluded.labels,
    meta = excluded.meta,
    adapter = excluded.adapter
`

type InsertEntityStateParams struct {
	ID        string `json:"id"`
	EntityID  string `json:"entity_id"`
	ScopeID   string `json:"scope_id"`
	Timestamp string `json:"timestamp"`
	Features  string `json:"features"`
	Labels    string `json:"labels"`
	Meta      string `json:"meta"`
	Adapter   string `json:"adapter"`
	CreatedAt string `json:"created_at"`
}

func (q *Queries) InsertEntityState(ctx context.Context, arg InsertEntityStateParams) error {
	_, err := q.db.ExecContext(ctx, insertEntityState,
		arg.ID, arg.EntityID, arg.ScopeID, arg.Timestamp,
		arg.Features, arg.Labels, arg.Meta, arg.Adapter, arg.CreatedAt,
	)
	return err
}

const getSignalByID = `-- name: GetSignalByID :one
SELECT id, scope_id, series_id, pattern, detected_at, window_start, window_end, strength, confidence, metrics
FROM signals WHERE id = ?
`

func (q *Queries) GetSignalByID(ctx context.Context, id string) (Signal, error) {
	row := q.db.QueryRowContext(ctx, getSignalByID, id)
	var s Signal
	err := row.Scan(
		&s.ID, &s.ScopeID, &s.SeriesID, &s.Pattern, &s.DetectedAt,
		&s.WindowStart, &s.WindowEnd, &s.Strength, &s.Confidence, &s.Metrics,
	)
	return s, err
}

const getSignalEvidence = `-- name: GetSignalEvidence :many
SELECT signal_id, series_id, time, kind, score, metrics FROM signal_evidence
WHERE signal_id = ?
ORDER BY score DESC
`

func (q *Queries) GetSignalEvidence(ctx context.Context, signalID string) ([]SignalEvidence, error) {
	rows, err := q.db.QueryContext(ctx, getSignalEvidence, signalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SignalEvidence{}
	for rows.Next() {
		var e SignalEvidence
		if err := rows.Scan(&e.SignalID, &e.SeriesID, &e.Time, &e.Kind, &e.Score, &e.Metrics); err != nil {
			return nil, err
		}
		items = append(items, e)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertSignal = `-- name: InsertSignal :exec
INSERT INTO signals (id, scope_id, series_id, pattern, detected_at, window_start, window_end, strength, confidence, metrics)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    strength = excluded.strength,
    confidence = excluded.confidence,
    metrics = excluded.metrics
`

type InsertSignalParams struct {
	ID          string  `json:"id"`
	ScopeID     string  `json:"scope_id"`
	SeriesID    string  `json:"series_id"`
	Pattern     string  `json:"pattern"`
	DetectedAt  string  `json:"detected_at"`
	WindowStart string  `json:"window_start"`
	WindowEnd   string  `json:"window_end"`
	Strength    float64 `json:"strength"`
	Confidence  float64 `json:"confidence"`
	Metrics     string  `json:"metrics"`
}

func (q *Queries) InsertSignal(ctx context.Context, arg InsertSignalParams) error {
	_, err := q.db.ExecContext(ctx, insertSignal,
		arg.ID, arg.ScopeID, arg.SeriesID, arg.Pattern, arg.DetectedAt,
		arg.WindowStart, arg.WindowEnd, arg.Strength, arg.Confidence, arg.Metrics,
	)
	return err
}

const insertSignalEvidence = `-- name: InsertSignalEvidence :exec
INSERT INTO signal_evidence (signal_id, series_id, time, kind, score, metrics)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertSignalEvidenceParams struct {
	SignalID string  `json:"signal_id"`
	SeriesID string  `json:"series_id"`
	Time     string  `json:"time"`
	Kind     string  `json:"kind"`
	Score    float64 `json:"score"`
	Metrics  string  `json:"metrics"`
}

func (q *Queries) InsertSignalEvidence(ctx context.Context, arg InsertSignalEvidenceParams) error {
	_, err := q.db.ExecContext(ctx, insertSignalEvidence,
		arg.SignalID, arg.SeriesID, arg.Time, arg.Kind, arg.Score, arg.Metrics,
	)
	return err
}
