// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlite

import (
	"database/sql"
)

type EntityState struct {
	ID        string `json:"id"`
	EntityID  string `json:"entity_id"`
	ScopeID   string `json:"scope_id"`
	Timestamp string `json:"timestamp"`
	Features  string `json:"features"`
	Labels    string `json:"labels"`
	Meta      string `json:"meta"`
	Adapter   string `json:"adapter"`
	CreatedAt string `json:"created_at"`
}

type Insight struct {
	ID            string  `json:"id"`
	ScopeID       string  `json:"scope_id"`
	Type          string  `json:"type"`
	SubjectEntity string  `json:"subject_entity"`
	SubjectTime   string  `json:"subject_time"`
	SampleSize    int64   `json:"sample_size"`
	Confidence    float64 `json:"confidence"`
	Title         string  `json:"title"`
	Summary       string  `json:"summary"`
	Suggestion    string  `json:"suggestion"`
	GeneratedAt   string  `json:"generated_at"`
	ValidUntil    string  `json:"valid_until"`
	DismissedAt   string  `json:"dismissed_at"`
	DismissedBy   string  `json:"dismissed_by"`
}

type InsightCase struct {
	InsightID   string          `json:"insight_id"`
	EntityID    string          `json:"entity_id"`
	CaseTime    string          `json:"case_time"`
	Similarity  float64         `json:"similarity"`
	OutcomeDiff sql.NullFloat64 `json:"outcome_diff"`
}

type InsightFeedback struct {
	InsightID string        `json:"insight_id"`
	Useful    sql.NullInt64 `json:"useful"`
	Applied   sql.NullInt64 `json:"applied"`
	Reason    string        `json:"reason"`
	CreatedAt string        `json:"created_at"`
}

type InsightsFt struct {
	Title   string `json:"title"`
	Summary string `json:"summary"`
}

type Similarity struct {
	ID         string  `json:"id"`
	StateAID   string  `json:"state_a_id"`
	StateBID   string  `json:"state_b_id"`
	Similarity float64 `json:"similarity"`
	ComputedAt string  `json:"computed_at"`
}
