// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlite

import (
	"context"
	"database/sql"
)

const countEntityStates = `-- name: CountEntityStates :one
SELECT COUNT(*) FROM entity_states WHERE adapter = ?
`

func (q *Queries) CountEntityStates(ctx context.Context, adapter string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEntityStates, adapter)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countInsights = `-- name: CountInsights :one
SELECT COUNT(*) FROM insights WHERE scope_id = ?
`

func (q *Queries) CountInsights(ctx context.Context, scopeID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countInsights, scopeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteOldEntityStates = `-- name: DeleteOldEntityStates :exec
DELETE FROM entity_states
WHERE timestamp < ? AND adapter = ?
`

type DeleteOldEntityStatesParams struct {
	Timestamp string `json:"timestamp"`
	Adapter   string `json:"adapter"`
}

func (q *Queries) DeleteOldEntityStates(ctx context.Context, arg DeleteOldEntityStatesParams) error {
	_, err := q.db.ExecContext(ctx, deleteOldEntityStates, arg.Timestamp, arg.Adapter)
	return err
}

const dismissInsight = `-- name: DismissInsight :exec
UPDATE insights SET dismissed_at = ?, dismissed_by = ? WHERE id = ?
`

type DismissInsightParams struct {
	DismissedAt string `json:"dismissed_at"`
	DismissedBy string `json:"dismissed_by"`
	ID          string `json:"id"`
}

func (q *Queries) DismissInsight(ctx context.Context, arg DismissInsightParams) error {
	_, err := q.db.ExecContext(ctx, dismissInsight, arg.DismissedAt, arg.DismissedBy, arg.ID)
	return err
}

const getEntityStatesByEntity = `-- name: GetEntityStatesByEntity :many
SELECT id, entity_id, scope_id, timestamp, features, labels, meta, adapter, created_at FROM entity_states
WHERE entity_id = ?
ORDER BY timestamp DESC
`

func (q *Queries) GetEntityStatesByEntity(ctx context.Context, entityID string) ([]EntityState, error) {
	rows, err := q.db.QueryContext(ctx, getEntityStatesByEntity, entityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EntityState{}
	for rows.Next() {
		var i EntityState
		if err := rows.Scan(
			&i.ID,
			&i.EntityID,
			&i.ScopeID,
			&i.Timestamp,
			&i.Features,
			&i.Labels,
			&i.Meta,
			&i.Adapter,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntityStatesByScope = `-- name: GetEntityStatesByScope :many
SELECT id, entity_id, scope_id, timestamp, features, labels, meta, adapter, created_at FROM entity_states
WHERE scope_id = ?
ORDER BY timestamp DESC
`

func (q *Queries) GetEntityStatesByScope(ctx context.Context, scopeID string) ([]EntityState, error) {
	rows, err := q.db.QueryContext(ctx, getEntityStatesByScope, scopeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EntityState{}
	for rows.Next() {
		var i EntityState
		if err := rows.Scan(
			&i.ID,
			&i.EntityID,
			&i.ScopeID,
			&i.Timestamp,
			&i.Features,
			&i.Labels,
			&i.Meta,
			&i.Adapter,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFeedbackByInsight = `-- name: GetFeedbackByInsight :one
SELECT insight_id, useful, applied, reason, created_at FROM insight_feedback WHERE insight_id = ?
`

func (q *Queries) GetFeedbackByInsight(ctx context.Context, insightID string) (InsightFeedback, error) {
	row := q.db.QueryRowContext(ctx, getFeedbackByInsight, insightID)
	var i InsightFeedback
	err := row.Scan(
		&i.InsightID,
		&i.Useful,
		&i.Applied,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const getInsightByID = `-- name: GetInsightByID :one
SELECT id, scope_id, type, subject_entity, subject_time, sample_size, confidence, title, summary, suggestion, generated_at, valid_until, dismissed_at, dismissed_by FROM insights WHERE id = ?
`

func (q *Queries) GetInsightByID(ctx context.Context, id string) (Insight, error) {
	row := q.db.QueryRowContext(ctx, getInsightByID, id)
	var i Insight
	err := row.Scan(
		&i.ID,
		&i.ScopeID,
		&i.Type,
		&i.SubjectEntity,
		&i.SubjectTime,
		&i.SampleSize,
		&i.Confidence,
		&i.Title,
		&i.Summary,
		&i.Suggestion,
		&i.GeneratedAt,
		&i.ValidUntil,
		&i.DismissedAt,
		&i.DismissedBy,
	)
	return i, err
}

const getInsightsByScope = `-- name: GetInsightsByScope :many
SELECT id, scope_id, type, subject_entity, subject_time, sample_size, confidence, title, summary, suggestion, generated_at, valid_until, dismissed_at, dismissed_by FROM insights
WHERE scope_id = ? AND dismissed_at IS NULL
ORDER BY confidence DESC, generated_at DESC
`

func (q *Queries) GetInsightsByScope(ctx context.Context, scopeID string) ([]Insight, error) {
	rows, err := q.db.QueryContext(ctx, getInsightsByScope, scopeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Insight{}
	for rows.Next() {
		var i Insight
		if err := rows.Scan(
			&i.ID,
			&i.ScopeID,
			&i.Type,
			&i.SubjectEntity,
			&i.SubjectTime,
			&i.SampleSize,
			&i.Confidence,
			&i.Title,
			&i.Summary,
			&i.Suggestion,
			&i.GeneratedAt,
			&i.ValidUntil,
			&i.DismissedAt,
			&i.DismissedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSimilaritiesByState = `-- name: GetSimilaritiesByState :many
SELECT id, state_a_id, state_b_id, similarity, computed_at FROM similarities
WHERE state_a_id = ? OR state_b_id = ?
ORDER BY similarity DESC
`

type GetSimilaritiesByStateParams struct {
	StateAID string `json:"state_a_id"`
	StateBID string `json:"state_b_id"`
}

func (q *Queries) GetSimilaritiesByState(ctx context.Context, arg GetSimilaritiesByStateParams) ([]Similarity, error) {
	rows, err := q.db.QueryContext(ctx, getSimilaritiesByState, arg.StateAID, arg.StateBID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Similarity{}
	for rows.Next() {
		var i Similarity
		if err := rows.Scan(
			&i.ID,
			&i.StateAID,
			&i.StateBID,
			&i.Similarity,
			&i.ComputedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertEntityState = `-- name: InsertEntityState :exec
INSERT INTO entity_states (id, entity_id, scope_id, timestamp, features, labels, meta, adapter, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertEntityStateParams struct {
	ID        string `json:"id"`
	EntityID  string `json:"entity_id"`
	ScopeID   string `json:"scope_id"`
	Timestamp string `json:"timestamp"`
	Features  string `json:"features"`
	Labels    string `json:"labels"`
	Meta      string `json:"meta"`
	Adapter   string `json:"adapter"`
	CreatedAt string `json:"created_at"`
}

func (q *Queries) InsertEntityState(ctx context.Context, arg InsertEntityStateParams) error {
	_, err := q.db.ExecContext(ctx, insertEntityState,
		arg.ID,
		arg.EntityID,
		arg.ScopeID,
		arg.Timestamp,
		arg.Features,
		arg.Labels,
		arg.Meta,
		arg.Adapter,
		arg.CreatedAt,
	)
	return err
}

const insertInsight = `-- name: InsertInsight :exec
INSERT INTO insights (id, scope_id, type, subject_entity, subject_time, sample_size, confidence, title, summary, suggestion, generated_at, valid_until)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertInsightParams struct {
	ID            string  `json:"id"`
	ScopeID       string  `json:"scope_id"`
	Type          string  `json:"type"`
	SubjectEntity string  `json:"subject_entity"`
	SubjectTime   string  `json:"subject_time"`
	SampleSize    int64   `json:"sample_size"`
	Confidence    float64 `json:"confidence"`
	Title         string  `json:"title"`
	Summary       string  `json:"summary"`
	Suggestion    string  `json:"suggestion"`
	GeneratedAt   string  `json:"generated_at"`
	ValidUntil    string  `json:"valid_until"`
}

func (q *Queries) InsertInsight(ctx context.Context, arg InsertInsightParams) error {
	_, err := q.db.ExecContext(ctx, insertInsight,
		arg.ID,
		arg.ScopeID,
		arg.Type,
		arg.SubjectEntity,
		arg.SubjectTime,
		arg.SampleSize,
		arg.Confidence,
		arg.Title,
		arg.Summary,
		arg.Suggestion,
		arg.GeneratedAt,
		arg.ValidUntil,
	)
	return err
}

const insertInsightCase = `-- name: InsertInsightCase :exec
INSERT INTO insight_cases (insight_id, entity_id, case_time, similarity, outcome_diff)
VALUES (?, ?, ?, ?, ?)
`

type InsertInsightCaseParams struct {
	InsightID   string          `json:"insight_id"`
	EntityID    string          `json:"entity_id"`
	CaseTime    string          `json:"case_time"`
	Similarity  float64         `json:"similarity"`
	OutcomeDiff sql.NullFloat64 `json:"outcome_diff"`
}

func (q *Queries) InsertInsightCase(ctx context.Context, arg InsertInsightCaseParams) error {
	_, err := q.db.ExecContext(ctx, insertInsightCase,
		arg.InsightID,
		arg.EntityID,
		arg.CaseTime,
		arg.Similarity,
		arg.OutcomeDiff,
	)
	return err
}

const insertSimilarity = `-- name: InsertSimilarity :exec
INSERT INTO similarities (id, state_a_id, state_b_id, similarity, computed_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(state_a_id, state_b_id) DO UPDATE SET
    similarity = excluded.similarity,
    computed_at = excluded.computed_at
`

type InsertSimilarityParams struct {
	ID         string  `json:"id"`
	StateAID   string  `json:"state_a_id"`
	StateBID   string  `json:"state_b_id"`
	Similarity float64 `json:"similarity"`
	ComputedAt string  `json:"computed_at"`
}

func (q *Queries) InsertSimilarity(ctx context.Context, arg InsertSimilarityParams) error {
	_, err := q.db.ExecContext(ctx, insertSimilarity,
		arg.ID,
		arg.StateAID,
		arg.StateBID,
		arg.Similarity,
		arg.ComputedAt,
	)
	return err
}

const upsertFeedback = `-- name: UpsertFeedback :exec
INSERT INTO insight_feedback (insight_id, useful, applied, reason, created_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(insight_id) DO UPDATE SET
    useful = excluded.useful,
    applied = excluded.applied,
    reason = excluded.reason,
    created_at = excluded.created_at
`

type UpsertFeedbackParams struct {
	InsightID string        `json:"insight_id"`
	Useful    sql.NullInt64 `json:"useful"`
	Applied   sql.NullInt64 `json:"applied"`
	Reason    string        `json:"reason"`
	CreatedAt string        `json:"created_at"`
}

func (q *Queries) UpsertFeedback(ctx context.Context, arg UpsertFeedbackParams) error {
	_, err := q.db.ExecContext(ctx, upsertFeedback,
		arg.InsightID,
		arg.Useful,
		arg.Applied,
		arg.Reason,
		arg.CreatedAt,
	)
	return err
}
