// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlite

import (
	"context"
)

type Querier interface {
	CountEntityStates(ctx context.Context, adapter string) (int64, error)
	CountInsights(ctx context.Context, scopeID string) (int64, error)
	DeleteOldEntityStates(ctx context.Context, arg DeleteOldEntityStatesParams) error
	DismissInsight(ctx context.Context, arg DismissInsightParams) error
	GetEntityStatesByEntity(ctx context.Context, entityID string) ([]EntityState, error)
	GetEntityStatesByScope(ctx context.Context, scopeID string) ([]EntityState, error)
	GetFeedbackByInsight(ctx context.Context, insightID string) (InsightFeedback, error)
	GetInsightByID(ctx context.Context, id string) (Insight, error)
	GetInsightsByScope(ctx context.Context, scopeID string) ([]Insight, error)
	GetSimilaritiesByState(ctx context.Context, arg GetSimilaritiesByStateParams) ([]Similarity, error)
	InsertEntityState(ctx context.Context, arg InsertEntityStateParams) error
	InsertInsight(ctx context.Context, arg InsertInsightParams) error
	InsertInsightCase(ctx context.Context, arg InsertInsightCaseParams) error
	InsertSimilarity(ctx context.Context, arg InsertSimilarityParams) error
	UpsertFeedback(ctx context.Context, arg UpsertFeedbackParams) error
}

var _ Querier = (*Queries)(nil)
