// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: api/proto/chronos/v1/chronos.proto

package chronosv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChronosService_Ingest_FullMethodName      = "/chronos.v1.ChronosService/Ingest"
	ChronosService_ListSignals_FullMethodName = "/chronos.v1.ChronosService/ListSignals"
	ChronosService_GetSignal_FullMethodName   = "/chronos.v1.ChronosService/GetSignal"
)

// ChronosServiceClient is the client API for ChronosService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ChronosService is the gRPC transport for the Chronos perception engine.
// It mirrors the HTTP REST surface: ingest observations and query signals.
// The service is signals-only: no Title, Summary, Suggestion, or dismissal.
type ChronosServiceClient interface {
	// Ingest persists a single EntityState observation. Detection is not
	// triggered automatically; the scheduler or compute pipeline handles
	// detection separately.
	Ingest(ctx context.Context, in *IngestRequest, opts ...grpc.CallOption) (*IngestResponse, error)
	// ListSignals returns signals matching the provided filter.
	ListSignals(ctx context.Context, in *ListSignalsRequest, opts ...grpc.CallOption) (*ListSignalsResponse, error)
	// GetSignal returns a single signal by ID.
	GetSignal(ctx context.Context, in *GetSignalRequest, opts ...grpc.CallOption) (*Signal, error)
}

type chronosServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChronosServiceClient(cc grpc.ClientConnInterface) ChronosServiceClient {
	return &chronosServiceClient{cc}
}

func (c *chronosServiceClient) Ingest(ctx context.Context, in *IngestRequest, opts ...grpc.CallOption) (*IngestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IngestResponse)
	err := c.cc.Invoke(ctx, ChronosService_Ingest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chronosServiceClient) ListSignals(ctx context.Context, in *ListSignalsRequest, opts ...grpc.CallOption) (*ListSignalsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSignalsResponse)
	err := c.cc.Invoke(ctx, ChronosService_ListSignals_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chronosServiceClient) GetSignal(ctx context.Context, in *GetSignalRequest, opts ...grpc.CallOption) (*Signal, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Signal)
	err := c.cc.Invoke(ctx, ChronosService_GetSignal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChronosServiceServer is the server API for ChronosService service.
// All implementations must embed UnimplementedChronosServiceServer
// for forward compatibility.
//
// ChronosService is the gRPC transport for the Chronos perception engine.
// It mirrors the HTTP REST surface: ingest observations and query signals.
// The service is signals-only: no Title, Summary, Suggestion, or dismissal.
type ChronosServiceServer interface {
	// Ingest persists a single EntityState observation. Detection is not
	// triggered automatically; the scheduler or compute pipeline handles
	// detection separately.
	Ingest(context.Context, *IngestRequest) (*IngestResponse, error)
	// ListSignals returns signals matching the provided filter.
	ListSignals(context.Context, *ListSignalsRequest) (*ListSignalsResponse, error)
	// GetSignal returns a single signal by ID.
	GetSignal(context.Context, *GetSignalRequest) (*Signal, error)
	mustEmbedUnimplementedChronosServiceServer()
}

// UnimplementedChronosServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChronosServiceServer struct{}

func (UnimplementedChronosServiceServer) Ingest(context.Context, *IngestRequest) (*IngestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ingest not implemented")
}
func (UnimplementedChronosServiceServer) ListSignals(context.Context, *ListSignalsRequest) (*ListSignalsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSignals not implemented")
}
func (UnimplementedChronosServiceServer) GetSignal(context.Context, *GetSignalRequest) (*Signal, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSignal not implemented")
}
func (UnimplementedChronosServiceServer) mustEmbedUnimplementedChronosServiceServer() {}
func (UnimplementedChronosServiceServer) testEmbeddedByValue()                        {}

// UnsafeChronosServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChronosServiceServer will
// result in compilation errors.
type UnsafeChronosServiceServer interface {
	mustEmbedUnimplementedChronosServiceServer()
}

func RegisterChronosServiceServer(s grpc.ServiceRegistrar, srv ChronosServiceServer) {
	// If the following call panics, it indicates UnimplementedChronosServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChronosService_ServiceDesc, srv)
}

func _ChronosService_Ingest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IngestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChronosServiceServer).Ingest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChronosService_Ingest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChronosServiceServer).Ingest(ctx, req.(*IngestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChronosService_ListSignals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSignalsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChronosServiceServer).ListSignals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChronosService_ListSignals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChronosServiceServer).ListSignals(ctx, req.(*ListSignalsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChronosService_GetSignal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSignalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChronosServiceServer).GetSignal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChronosService_GetSignal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChronosServiceServer).GetSignal(ctx, req.(*GetSignalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ChronosService_ServiceDesc is the grpc.ServiceDesc for ChronosService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChronosService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chronos.v1.ChronosService",
	HandlerType: (*ChronosServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ingest",
			Handler:    _ChronosService_Ingest_Handler,
		},
		{
			MethodName: "ListSignals",
			Handler:    _ChronosService_ListSignals_Handler,
		},
		{
			MethodName: "GetSignal",
			Handler:    _ChronosService_GetSignal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/chronos/v1/chronos.proto",
}
