// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/proto/chronos/v1/chronos.proto

package chronosv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PatternType is the enum mirror of domain.PatternType.
type PatternType int32

const (
	PatternType_PATTERN_TYPE_UNSPECIFIED             PatternType = 0
	PatternType_PATTERN_TYPE_RECURRENCE              PatternType = 1
	PatternType_PATTERN_TYPE_TREND                   PatternType = 2
	PatternType_PATTERN_TYPE_SPIKE                   PatternType = 3
	PatternType_PATTERN_TYPE_DROP                    PatternType = 4
	PatternType_PATTERN_TYPE_STALL                   PatternType = 5
	PatternType_PATTERN_TYPE_ANOMALY                 PatternType = 6
	PatternType_PATTERN_TYPE_SEASONALITY             PatternType = 7
	PatternType_PATTERN_TYPE_CORRELATION             PatternType = 8
	PatternType_PATTERN_TYPE_CHANGE_POINT            PatternType = 9
	PatternType_PATTERN_TYPE_OUTLIER_CLUSTER         PatternType = 10
	PatternType_PATTERN_TYPE_CROSS_SCOPE_CORRELATION PatternType = 11
)

// Enum value maps for PatternType.
var (
	PatternType_name = map[int32]string{
		0:  "PATTERN_TYPE_UNSPECIFIED",
		1:  "PATTERN_TYPE_RECURRENCE",
		2:  "PATTERN_TYPE_TREND",
		3:  "PATTERN_TYPE_SPIKE",
		4:  "PATTERN_TYPE_DROP",
		5:  "PATTERN_TYPE_STALL",
		6:  "PATTERN_TYPE_ANOMALY",
		7:  "PATTERN_TYPE_SEASONALITY",
		8:  "PATTERN_TYPE_CORRELATION",
		9:  "PATTERN_TYPE_CHANGE_POINT",
		10: "PATTERN_TYPE_OUTLIER_CLUSTER",
		11: "PATTERN_TYPE_CROSS_SCOPE_CORRELATION",
	}
	PatternType_value = map[string]int32{
		"PATTERN_TYPE_UNSPECIFIED":             0,
		"PATTERN_TYPE_RECURRENCE":              1,
		"PATTERN_TYPE_TREND":                   2,
		"PATTERN_TYPE_SPIKE":                   3,
		"PATTERN_TYPE_DROP":                    4,
		"PATTERN_TYPE_STALL":                   5,
		"PATTERN_TYPE_ANOMALY":                 6,
		"PATTERN_TYPE_SEASONALITY":             7,
		"PATTERN_TYPE_CORRELATION":             8,
		"PATTERN_TYPE_CHANGE_POINT":            9,
		"PATTERN_TYPE_OUTLIER_CLUSTER":         10,
		"PATTERN_TYPE_CROSS_SCOPE_CORRELATION": 11,
	}
)

func (x PatternType) Enum() *PatternType {
	p := new(PatternType)
	*p = x
	return p
}

func (x PatternType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PatternType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_chronos_v1_chronos_proto_enumTypes[0].Descriptor()
}

func (PatternType) Type() protoreflect.EnumType {
	return &file_api_proto_chronos_v1_chronos_proto_enumTypes[0]
}

func (x PatternType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PatternType.Descriptor instead.
func (PatternType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_chronos_v1_chronos_proto_rawDescGZIP(), []int{0}
}

// EntityState is a single observation of an entity at a point in time.
type EntityState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                             // UUID
	EntityId      string                 `protobuf:"bytes,2,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"` // UUID
	ScopeId       string                 `protobuf:"bytes,3,opt,name=scope_id,json=scopeId,proto3" json:"scope_id,omitempty"`    // UUID
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Features      []float64              `protobuf:"fixed64,5,rep,packed,name=features,proto3" json:"features,omitempty"`
	Labels        []string               `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty"`
	Meta          map[string]string      `protobuf:"bytes,7,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityState) Reset() {
	*x = EntityState{}
	mi := &file_api_proto_chronos_v1_chronos_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityState) ProtoMessage() {}

func (x *EntityState) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chronos_v1_chronos_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityState.ProtoReflect.Descriptor instead.
func (*EntityState) Descriptor() ([]byte, []int) {
	return file_api_proto_chronos_v1_chronos_proto_rawDescGZIP(), []int{0}
}

func (x *EntityState) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EntityState) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *EntityState) GetScopeId() string {
	if x != nil {
		return x.ScopeId
	}
	return ""
}

func (x *EntityState) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *EntityState) GetFeatures() []float64 {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *EntityState) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *EntityState) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

// Signal is a structured description of a detected pattern.
type Signal struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Id         string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                          // UUID
	ScopeId    string                 `protobuf:"bytes,2,opt,name=scope_id,json=scopeId,proto3" json:"scope_id,omitempty"` // UUID
	Series     string                 `protobuf:"bytes,3,opt,name=series,proto3" json:"series,omitempty"`                  // UUID — the entity the pattern was detected in
	Pattern    PatternType            `protobuf:"varint,4,opt,name=pattern,proto3,enum=chronos.v1.PatternType" json:"pattern,omitempty"`
	DetectedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=detected_at,json=detectedAt,proto3" json:"detected_at,omitempty"`
	Window     *TimeWindow            `protobuf:"bytes,6,opt,name=window,proto3" json:"window,omitempty"`
	Strength   float64                `protobuf:"fixed64,7,opt,name=strength,proto3" json:"strength,omitempty"`
	Confidence float64                `protobuf:"fixed64,8,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Metrics    map[string]float64     `protobuf:"bytes,9,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	Evidence   []*Evidence            `protobuf:"bytes,10,rep,name=evidence,proto3" json:"evidence,omitempty"`
	// Optional detector-side context that lets downstream consumers
	// narrate WHY the signal fired without re-deriving the data. Empty
	// when the detector did not surface one.
	Explanation *Explanation `protobuf:"bytes,11,opt,name=explanation,proto3" json:"explanation,omitempty"`
	// Qualitative grade the detector assigned ("tentative" |
	// "established" | "strong") based on sample size vs MIN_POINTS.
	// Empty when the detector did not classify; consumers treat absent
	// as "no claim about strength".
	ConfidenceClass string `protobuf:"bytes,12,opt,name=confidence_class,json=confidenceClass,proto3" json:"confidence_class,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Signal) Reset() {
	*x = Signal{}
	mi := &file_api_proto_chronos_v1_chronos_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Signal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signal) ProtoMessage() {}

func (x *Signal) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chronos_v1_chronos_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signal.ProtoReflect.Descriptor instead.
func (*Signal) Descriptor() ([]byte, []int) {
	return file_api_proto_chronos_v1_chronos_proto_rawDescGZIP(), []int{1}
}

func (x *Signal) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Signal) GetScopeId() string {
	if x != nil {
		return x.ScopeId
	}
	return ""
}

func (x *Signal) GetSeries() string {
	if x != nil {
		return x.Series
	}
	return ""
}

func (x *Signal) GetPattern() PatternType {
	if x != nil {
		return x.Pattern
	}
	return PatternType_PATTERN_TYPE_UNSPECIFIED
}

func (x *Signal) GetDetectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DetectedAt
	}
	return nil
}

func (x *Signal) GetWindow() *TimeWindow {
	if x != nil {
		return x.Window
	}
	return nil
}

func (x *Signal) GetStrength() float64 {
	if x != nil {
		return x.Strength
	}
	return 0
}

func (x *Signal) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Signal) GetMetrics() map[string]float64 {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *Signal) GetEvidence() []*Evidence {
	if x != nil {
		return x.Evidence
	}
	return nil
}

func (x *Signal) GetExplanation() *Explanation {
	if x != nil {
		return x.Explanation
	}
	return nil
}

func (x *Signal) GetConfidenceClass() string {
	if x != nil {
		return x.ConfidenceClass
	}
	return ""
}

// FeatureSample is one observation in the feature-evolution series the
// detector inspected.
type FeatureSample struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	At            *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=at,proto3" json:"at,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeatureSample) Reset() {
	*x = FeatureSample{}
	mi := &file_api_proto_chronos_v1_chronos_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeatureSample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeatureSample) ProtoMessage() {}

func (x *FeatureSample) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chronos_v1_chronos_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeatureSample.ProtoReflect.Descriptor instead.
func (*FeatureSample) Descriptor() ([]byte, []int) {
	return file_api_proto_chronos_v1_chronos_proto_rawDescGZIP(), []int{2}
}

func (x *FeatureSample) GetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.At
	}
	return nil
}

func (x *FeatureSample) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

// Explanation carries the detector-side context that produced a Signal:
// the feature evolution it saw, the peer cohort it compared against,
// the baseline window length, the threshold it crossed, and a stable
// version string for the detector. All fields are optional.
type Explanation struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	FeatureEvolution   []*FeatureSample       `protobuf:"bytes,1,rep,name=feature_evolution,json=featureEvolution,proto3" json:"feature_evolution,omitempty"`
	ComparablePeers    int32                  `protobuf:"varint,2,opt,name=comparable_peers,json=comparablePeers,proto3" json:"comparable_peers,omitempty"`
	BaselineWindowDays int32                  `protobuf:"varint,3,opt,name=baseline_window_days,json=baselineWindowDays,proto3" json:"baseline_window_days,omitempty"`
	ThresholdUsed      float64                `protobuf:"fixed64,4,opt,name=threshold_used,json=thresholdUsed,proto3" json:"threshold_used,omitempty"`
	DetectorVersion    string                 `protobuf:"bytes,5,opt,name=detector_version,json=detectorVersion,proto3" json:"detector_version,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Explanation) Reset() {
	*x = Explanation{}
	mi := &file_api_proto_chronos_v1_chronos_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Explanation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Explanation) ProtoMessage() {}

func (x *Explanation) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chronos_v1_chronos_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Explanation.ProtoReflect.Descriptor instead.
func (*Explanation) Descriptor() ([]byte, []int) {
	return file_api_proto_chronos_v1_chronos_proto_rawDescGZIP(), []int{3}
}

func (x *Explanation) GetFeatureEvolution() []*FeatureSample {
	if x != nil {
		return x.FeatureEvolution
	}
	return nil
}

func (x *Explanation) GetComparablePeers() int32 {
	if x != nil {
		return x.ComparablePeers
	}
	return 0
}

func (x *Explanation) GetBaselineWindowDays() int32 {
	if x != nil {
		return x.BaselineWindowDays
	}
	return 0
}

func (x *Explanation) GetThresholdUsed() float64 {
	if x != nil {
		return x.ThresholdUsed
	}
	return 0
}

func (x *Explanation) GetDetectorVersion() string {
	if x != nil {
		return x.DetectorVersion
	}
	return ""
}

// TimeWindow describes the analysis window over which a signal was detected.
type TimeWindow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End           *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeWindow) Reset() {
	*x = TimeWindow{}
	mi := &file_api_proto_chronos_v1_chronos_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeWindow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeWindow) ProtoMessage() {}

func (x *TimeWindow) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chronos_v1_chronos_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeWindow.ProtoReflect.Descriptor instead.
func (*TimeWindow) Descriptor() ([]byte, []int) {
	return file_api_proto_chronos_v1_chronos_proto_rawDescGZIP(), []int{4}
}

func (x *TimeWindow) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *TimeWindow) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

// Evidence is one piece of supporting data backing a signal.
type Evidence struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Series        string                 `protobuf:"bytes,1,opt,name=series,proto3" json:"series,omitempty"` // UUID
	Time          *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Score         float64                `protobuf:"fixed64,4,opt,name=score,proto3" json:"score,omitempty"`
	Metrics       map[string]float64     `protobuf:"bytes,5,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Evidence) Reset() {
	*x = Evidence{}
	mi := &file_api_proto_chronos_v1_chronos_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Evidence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Evidence) ProtoMessage() {}

func (x *Evidence) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chronos_v1_chronos_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Evidence.ProtoReflect.Descriptor instead.
func (*Evidence) Descriptor() ([]byte, []int) {
	return file_api_proto_chronos_v1_chronos_proto_rawDescGZIP(), []int{5}
}

func (x *Evidence) GetSeries() string {
	if x != nil {
		return x.Series
	}
	return ""
}

func (x *Evidence) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *Evidence) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Evidence) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Evidence) GetMetrics() map[string]float64 {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// IngestRequest is the wire shape for the Ingest RPC.
type IngestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                             // UUID; optional, server generates if empty
	EntityId      string                 `protobuf:"bytes,2,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"` // UUID
	ScopeId       string                 `protobuf:"bytes,3,opt,name=scope_id,json=scopeId,proto3" json:"scope_id,omitempty"`    // UUID
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`               // optional, server sets to now if not present
	Features      []float64              `protobuf:"fixed64,5,rep,packed,name=features,proto3" json:"features,omitempty"`
	Labels        []string               `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty"`
	Meta          map[string]string      `protobuf:"bytes,7,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Adapter       string                 `protobuf:"bytes,8,opt,name=adapter,proto3" json:"adapter,omitempty"` // source label; defaults to "grpc"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestRequest) Reset() {
	*x = IngestRequest{}
	mi := &file_api_proto_chronos_v1_chronos_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestRequest) ProtoMessage() {}

func (x *IngestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chronos_v1_chronos_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestRequest.ProtoReflect.Descriptor instead.
func (*IngestRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_chronos_v1_chronos_proto_rawDescGZIP(), []int{6}
}

func (x *IngestRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *IngestRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *IngestRequest) GetScopeId() string {
	if x != nil {
		return x.ScopeId
	}
	return ""
}

func (x *IngestRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *IngestRequest) GetFeatures() []float64 {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *IngestRequest) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *IngestRequest) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *IngestRequest) GetAdapter() string {
	if x != nil {
		return x.Adapter
	}
	return ""
}

// IngestResponse confirms persistence.
type IngestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestResponse) Reset() {
	*x = IngestResponse{}
	mi := &file_api_proto_chronos_v1_chronos_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestResponse) ProtoMessage() {}

func (x *IngestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chronos_v1_chronos_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestResponse.ProtoReflect.Descriptor instead.
func (*IngestResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_chronos_v1_chronos_proto_rawDescGZIP(), []int{7}
}

func (x *IngestResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *IngestResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// ListSignalsRequest filters the signals store.
type ListSignalsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScopeId       string                 `protobuf:"bytes,1,opt,name=scope_id,json=scopeId,proto3" json:"scope_id,omitempty"`                     // UUID; required unless scope_ids is set
	Series        string                 `protobuf:"bytes,2,opt,name=series,proto3" json:"series,omitempty"`                                      // UUID; optional
	Pattern       PatternType            `protobuf:"varint,3,opt,name=pattern,proto3,enum=chronos.v1.PatternType" json:"pattern,omitempty"`       // optional
	Since         *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=since,proto3" json:"since,omitempty"`                                        // optional
	Until         *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=until,proto3" json:"until,omitempty"`                                        // optional
	MinConfidence float64                `protobuf:"fixed64,6,opt,name=min_confidence,json=minConfidence,proto3" json:"min_confidence,omitempty"` // optional
	Limit         int32                  `protobuf:"varint,7,opt,name=limit,proto3" json:"limit,omitempty"`                                       // 0 = no limit
	// scope_ids: server-side allowlist for multi-scope queries. Use when
	// fetching across N entities owned by one consumer to avoid the N+1
	// round-trip pattern. At least one of scope_id or scope_ids must be
	// set.
	ScopeIds      []string `protobuf:"bytes,8,rep,name=scope_ids,json=scopeIds,proto3" json:"scope_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSignalsRequest) Reset() {
	*x = ListSignalsRequest{}
	mi := &file_api_proto_chronos_v1_chronos_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSignalsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSignalsRequest) ProtoMessage() {}

func (x *ListSignalsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chronos_v1_chronos_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSignalsRequest.ProtoReflect.Descriptor instead.
func (*ListSignalsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_chronos_v1_chronos_proto_rawDescGZIP(), []int{8}
}

func (x *ListSignalsRequest) GetScopeId() string {
	if x != nil {
		return x.ScopeId
	}
	return ""
}

func (x *ListSignalsRequest) GetSeries() string {
	if x != nil {
		return x.Series
	}
	return ""
}

func (x *ListSignalsRequest) GetPattern() PatternType {
	if x != nil {
		return x.Pattern
	}
	return PatternType_PATTERN_TYPE_UNSPECIFIED
}

func (x *ListSignalsRequest) GetSince() *timestamppb.Timestamp {
	if x != nil {
		return x.Since
	}
	return nil
}

func (x *ListSignalsRequest) GetUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.Until
	}
	return nil
}

func (x *ListSignalsRequest) GetMinConfidence() float64 {
	if x != nil {
		return x.MinConfidence
	}
	return 0
}

func (x *ListSignalsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListSignalsRequest) GetScopeIds() []string {
	if x != nil {
		return x.ScopeIds
	}
	return nil
}

// ListSignalsResponse carries the matched signals.
type ListSignalsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signals       []*Signal              `protobuf:"bytes,1,rep,name=signals,proto3" json:"signals,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSignalsResponse) Reset() {
	*x = ListSignalsResponse{}
	mi := &file_api_proto_chronos_v1_chronos_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSignalsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSignalsResponse) ProtoMessage() {}

func (x *ListSignalsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chronos_v1_chronos_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSignalsResponse.ProtoReflect.Descriptor instead.
func (*ListSignalsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_chronos_v1_chronos_proto_rawDescGZIP(), []int{9}
}

func (x *ListSignalsResponse) GetSignals() []*Signal {
	if x != nil {
		return x.Signals
	}
	return nil
}

func (x *ListSignalsResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// GetSignalRequest looks up a single signal.
type GetSignalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // UUID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSignalRequest) Reset() {
	*x = GetSignalRequest{}
	mi := &file_api_proto_chronos_v1_chronos_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSignalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSignalRequest) ProtoMessage() {}

func (x *GetSignalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_chronos_v1_chronos_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSignalRequest.ProtoReflect.Descriptor instead.
func (*GetSignalRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_chronos_v1_chronos_proto_rawDescGZIP(), []int{10}
}

func (x *GetSignalRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_api_proto_chronos_v1_chronos_proto protoreflect.FileDescriptor

const file_api_proto_chronos_v1_chronos_proto_rawDesc = "" +
	"\n" +
	"\"api/proto/chronos/v1/chronos.proto\x12\n" +
	"chronos.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb3\x02\n" +
	"\vEntityState\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tentity_id\x18\x02 \x01(\tR\bentityId\x12\x19\n" +
	"\bscope_id\x18\x03 \x01(\tR\ascopeId\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1a\n" +
	"\bfeatures\x18\x05 \x03(\x01R\bfeatures\x12\x16\n" +
	"\x06labels\x18\x06 \x03(\tR\x06labels\x125\n" +
	"\x04meta\x18\a \x03(\v2!.chronos.v1.EntityState.MetaEntryR\x04meta\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb6\x04\n" +
	"\x06Signal\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bscope_id\x18\x02 \x01(\tR\ascopeId\x12\x16\n" +
	"\x06series\x18\x03 \x01(\tR\x06series\x121\n" +
	"\apattern\x18\x04 \x01(\x0e2\x17.chronos.v1.PatternTypeR\apattern\x12;\n" +
	"\vdetected_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"detectedAt\x12.\n" +
	"\x06window\x18\x06 \x01(\v2\x16.chronos.v1.TimeWindowR\x06window\x12\x1a\n" +
	"\bstrength\x18\a \x01(\x01R\bstrength\x12\x1e\n" +
	"\n" +
	"confidence\x18\b \x01(\x01R\n" +
	"confidence\x129\n" +
	"\ametrics\x18\t \x03(\v2\x1f.chronos.v1.Signal.MetricsEntryR\ametrics\x120\n" +
	"\bevidence\x18\n" +
	" \x03(\v2\x14.chronos.v1.EvidenceR\bevidence\x129\n" +
	"\vexplanation\x18\v \x01(\v2\x17.chronos.v1.ExplanationR\vexplanation\x12)\n" +
	"\x10confidence_class\x18\f \x01(\tR\x0fconfidenceClass\x1a:\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"Q\n" +
	"\rFeatureSample\x12*\n" +
	"\x02at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x02at\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\"\x84\x02\n" +
	"\vExplanation\x12F\n" +
	"\x11feature_evolution\x18\x01 \x03(\v2\x19.chronos.v1.FeatureSampleR\x10featureEvolution\x12)\n" +
	"\x10comparable_peers\x18\x02 \x01(\x05R\x0fcomparablePeers\x120\n" +
	"\x14baseline_window_days\x18\x03 \x01(\x05R\x12baselineWindowDays\x12%\n" +
	"\x0ethreshold_used\x18\x04 \x01(\x01R\rthresholdUsed\x12)\n" +
	"\x10detector_version\x18\x05 \x01(\tR\x0fdetectorVersion\"l\n" +
	"\n" +
	"TimeWindow\x120\n" +
	"\x05start\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12,\n" +
	"\x03end\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x03end\"\xf5\x01\n" +
	"\bEvidence\x12\x16\n" +
	"\x06series\x18\x01 \x01(\tR\x06series\x12.\n" +
	"\x04time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x01R\x05score\x12;\n" +
	"\ametrics\x18\x05 \x03(\v2!.chronos.v1.Evidence.MetricsEntryR\ametrics\x1a:\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\xd1\x02\n" +
	"\rIngestRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tentity_id\x18\x02 \x01(\tR\bentityId\x12\x19\n" +
	"\bscope_id\x18\x03 \x01(\tR\ascopeId\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1a\n" +
	"\bfeatures\x18\x05 \x03(\x01R\bfeatures\x12\x16\n" +
	"\x06labels\x18\x06 \x03(\tR\x06labels\x127\n" +
	"\x04meta\x18\a \x03(\v2#.chronos.v1.IngestRequest.MetaEntryR\x04meta\x12\x18\n" +
	"\aadapter\x18\b \x01(\tR\aadapter\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"8\n" +
	"\x0eIngestResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\xb8\x02\n" +
	"\x12ListSignalsRequest\x12\x19\n" +
	"\bscope_id\x18\x01 \x01(\tR\ascopeId\x12\x16\n" +
	"\x06series\x18\x02 \x01(\tR\x06series\x121\n" +
	"\apattern\x18\x03 \x01(\x0e2\x17.chronos.v1.PatternTypeR\apattern\x120\n" +
	"\x05since\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x05since\x120\n" +
	"\x05until\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x05until\x12%\n" +
	"\x0emin_confidence\x18\x06 \x01(\x01R\rminConfidence\x12\x14\n" +
	"\x05limit\x18\a \x01(\x05R\x05limit\x12\x1b\n" +
	"\tscope_ids\x18\b \x03(\tR\bscopeIds\"Y\n" +
	"\x13ListSignalsResponse\x12,\n" +
	"\asignals\x18\x01 \x03(\v2\x12.chronos.v1.SignalR\asignals\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"\"\n" +
	"\x10GetSignalRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id*\xe8\x02\n" +
	"\vPatternType\x12\x1c\n" +
	"\x18PATTERN_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17PATTERN_TYPE_RECURRENCE\x10\x01\x12\x16\n" +
	"\x12PATTERN_TYPE_TREND\x10\x02\x12\x16\n" +
	"\x12PATTERN_TYPE_SPIKE\x10\x03\x12\x15\n" +
	"\x11PATTERN_TYPE_DROP\x10\x04\x12\x16\n" +
	"\x12PATTERN_TYPE_STALL\x10\x05\x12\x18\n" +
	"\x14PATTERN_TYPE_ANOMALY\x10\x06\x12\x1c\n" +
	"\x18PATTERN_TYPE_SEASONALITY\x10\a\x12\x1c\n" +
	"\x18PATTERN_TYPE_CORRELATION\x10\b\x12\x1d\n" +
	"\x19PATTERN_TYPE_CHANGE_POINT\x10\t\x12 \n" +
	"\x1cPATTERN_TYPE_OUTLIER_CLUSTER\x10\n" +
	"\x12(\n" +
	"$PATTERN_TYPE_CROSS_SCOPE_CORRELATION\x10\v2\xe0\x01\n" +
	"\x0eChronosService\x12?\n" +
	"\x06Ingest\x12\x19.chronos.v1.IngestRequest\x1a\x1a.chronos.v1.IngestResponse\x12N\n" +
	"\vListSignals\x12\x1e.chronos.v1.ListSignalsRequest\x1a\x1f.chronos.v1.ListSignalsResponse\x12=\n" +
	"\tGetSignal\x12\x1c.chronos.v1.GetSignalRequest\x1a\x12.chronos.v1.SignalBAZ?github.com/felixgeelhaar/chronos/api/proto/chronos/v1;chronosv1b\x06proto3"

var (
	file_api_proto_chronos_v1_chronos_proto_rawDescOnce sync.Once
	file_api_proto_chronos_v1_chronos_proto_rawDescData []byte
)

func file_api_proto_chronos_v1_chronos_proto_rawDescGZIP() []byte {
	file_api_proto_chronos_v1_chronos_proto_rawDescOnce.Do(func() {
		file_api_proto_chronos_v1_chronos_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_chronos_v1_chronos_proto_rawDesc), len(file_api_proto_chronos_v1_chronos_proto_rawDesc)))
	})
	return file_api_proto_chronos_v1_chronos_proto_rawDescData
}

var file_api_proto_chronos_v1_chronos_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_chronos_v1_chronos_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_api_proto_chronos_v1_chronos_proto_goTypes = []any{
	(PatternType)(0),              // 0: chronos.v1.PatternType
	(*EntityState)(nil),           // 1: chronos.v1.EntityState
	(*Signal)(nil),                // 2: chronos.v1.Signal
	(*FeatureSample)(nil),         // 3: chronos.v1.FeatureSample
	(*Explanation)(nil),           // 4: chronos.v1.Explanation
	(*TimeWindow)(nil),            // 5: chronos.v1.TimeWindow
	(*Evidence)(nil),              // 6: chronos.v1.Evidence
	(*IngestRequest)(nil),         // 7: chronos.v1.IngestRequest
	(*IngestResponse)(nil),        // 8: chronos.v1.IngestResponse
	(*ListSignalsRequest)(nil),    // 9: chronos.v1.ListSignalsRequest
	(*ListSignalsResponse)(nil),   // 10: chronos.v1.ListSignalsResponse
	(*GetSignalRequest)(nil),      // 11: chronos.v1.GetSignalRequest
	nil,                           // 12: chronos.v1.EntityState.MetaEntry
	nil,                           // 13: chronos.v1.Signal.MetricsEntry
	nil,                           // 14: chronos.v1.Evidence.MetricsEntry
	nil,                           // 15: chronos.v1.IngestRequest.MetaEntry
	(*timestamppb.Timestamp)(nil), // 16: google.protobuf.Timestamp
}
var file_api_proto_chronos_v1_chronos_proto_depIdxs = []int32{
	16, // 0: chronos.v1.EntityState.timestamp:type_name -> google.protobuf.Timestamp
	12, // 1: chronos.v1.EntityState.meta:type_name -> chronos.v1.EntityState.MetaEntry
	0,  // 2: chronos.v1.Signal.pattern:type_name -> chronos.v1.PatternType
	16, // 3: chronos.v1.Signal.detected_at:type_name -> google.protobuf.Timestamp
	5,  // 4: chronos.v1.Signal.window:type_name -> chronos.v1.TimeWindow
	13, // 5: chronos.v1.Signal.metrics:type_name -> chronos.v1.Signal.MetricsEntry
	6,  // 6: chronos.v1.Signal.evidence:type_name -> chronos.v1.Evidence
	4,  // 7: chronos.v1.Signal.explanation:type_name -> chronos.v1.Explanation
	16, // 8: chronos.v1.FeatureSample.at:type_name -> google.protobuf.Timestamp
	3,  // 9: chronos.v1.Explanation.feature_evolution:type_name -> chronos.v1.FeatureSample
	16, // 10: chronos.v1.TimeWindow.start:type_name -> google.protobuf.Timestamp
	16, // 11: chronos.v1.TimeWindow.end:type_name -> google.protobuf.Timestamp
	16, // 12: chronos.v1.Evidence.time:type_name -> google.protobuf.Timestamp
	14, // 13: chronos.v1.Evidence.metrics:type_name -> chronos.v1.Evidence.MetricsEntry
	16, // 14: chronos.v1.IngestRequest.timestamp:type_name -> google.protobuf.Timestamp
	15, // 15: chronos.v1.IngestRequest.meta:type_name -> chronos.v1.IngestRequest.MetaEntry
	0,  // 16: chronos.v1.ListSignalsRequest.pattern:type_name -> chronos.v1.PatternType
	16, // 17: chronos.v1.ListSignalsRequest.since:type_name -> google.protobuf.Timestamp
	16, // 18: chronos.v1.ListSignalsRequest.until:type_name -> google.protobuf.Timestamp
	2,  // 19: chronos.v1.ListSignalsResponse.signals:type_name -> chronos.v1.Signal
	7,  // 20: chronos.v1.ChronosService.Ingest:input_type -> chronos.v1.IngestRequest
	9,  // 21: chronos.v1.ChronosService.ListSignals:input_type -> chronos.v1.ListSignalsRequest
	11, // 22: chronos.v1.ChronosService.GetSignal:input_type -> chronos.v1.GetSignalRequest
	8,  // 23: chronos.v1.ChronosService.Ingest:output_type -> chronos.v1.IngestResponse
	10, // 24: chronos.v1.ChronosService.ListSignals:output_type -> chronos.v1.ListSignalsResponse
	2,  // 25: chronos.v1.ChronosService.GetSignal:output_type -> chronos.v1.Signal
	23, // [23:26] is the sub-list for method output_type
	20, // [20:23] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_api_proto_chronos_v1_chronos_proto_init() }
func file_api_proto_chronos_v1_chronos_proto_init() {
	if File_api_proto_chronos_v1_chronos_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_chronos_v1_chronos_proto_rawDesc), len(file_api_proto_chronos_v1_chronos_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_chronos_v1_chronos_proto_goTypes,
		DependencyIndexes: file_api_proto_chronos_v1_chronos_proto_depIdxs,
		EnumInfos:         file_api_proto_chronos_v1_chronos_proto_enumTypes,
		MessageInfos:      file_api_proto_chronos_v1_chronos_proto_msgTypes,
	}.Build()
	File_api_proto_chronos_v1_chronos_proto = out.File
	file_api_proto_chronos_v1_chronos_proto_goTypes = nil
	file_api_proto_chronos_v1_chronos_proto_depIdxs = nil
}
